# uncomment to preview locally
#theme: "just-the-docs"
remote_theme: dendronhq/dendron-jekyll
title: Dendron
logo: "/assets/images/logo.png"
exclude: [ "node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile", "*/dendron.template.release.md"
]
footer_content: "Copyright &copy; 2020 Thence LLC"
url: "https://www.dendron.so"

gh_edit_link: true 
gh_edit_repository: "https://github.com/dendronhq/dendron-template"
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_branch: "master" # the branch that your docs is served from
gh_root: "docs/" # doc root
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately
dendron_vault_path: "vault"

enable_mathjax: true
kramdown:
  math_engine: mathjax

# seo
tagline: "A better way to know"
description: "Dendron is a local-first, markdown based, hierarchical note taking tool. It is meant to help you create, organize, and collaborate on knowledge bases of any size."
twitter:
  card: summary
  username: dendronhq
author:
  twitter: dendronhq

defaults:
  -
    scope:
      path: "notes" # an empty string here means all files in the project
    values:
      layout: "default"
      image: "/assets/images/logo.png"