name: URL validator

on:
  push:
    branches:
    - master
    - main
  pull_request:
    branches:
    - master
    - main
    - dev

jobs:
  Pre-Commit:
    name: Run brok Against files in repo

    runs-on: ubuntu-latest

    container:
      image: debian:bullseye-slim

    steps:

    - name: Install System Deps
      run: |
        apt-get update
        apt-get install -y wget libtinfo5

    - uses: actions/checkout@v2

    - name: Get Date
      id: get-date
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%Y%m")"
      shell: bash
    - uses: actions/cache@v2
      with:
        path: .brokdb
        key: ${{ hashFiles('.github/workflows/url-auditor.yml') }}-${{ hashFiles('.brokignore') }}-${{ steps.get-date.outputs.date }}

    - name: Install brok
      run: |
        wget https://github.com/smallhadroncollider/brok/releases/download/1.1.0/brok-1.1.0_x86-64-linux.deb
        dpkg -i brok-1.1.0_x86-64-linux.deb
    - name: Run brok
      run: |
        brok --ignore $(cat .brokignore | grep -v '^#') $(find . -type f -name "*.yml") $(find path -type f -name "*.yml") $(find . -type f -name "*.md") > /dev/null
